### ISSUE TITLE
SyntaxError: Unexpected reserved word

### ISSUE THREAD

**Issue by bvanrijn** [nemo/natural-synaptic#1]
I get an error when I try to run the [the first example](https://www.npmjs.com/package/natural-synaptic#training-and-classifying):

```
barend@barend-eos:~/neural$ node index.js 

/home/barend/neural/node_modules/natural-synaptic/lib/index.js:10
class NaturalSynaptic extends ClassifierBase {
^^^^^
SyntaxError: Unexpected reserved word
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/barend/neural/index.js:1:63)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
```

The contents of `index.js`:

```
require('natural-synaptic');
var classifier = new NaturalSynaptic();

classifier.addDocument('my unit-tests failed.', 'software');
classifier.addDocument('tried the program, but it was buggy.', 'software');
classifier.addDocument('tomorrow we will do standup.', 'meeting');
classifier.addDocument('the drive has a 2TB capacity.', 'hardware');
classifier.addDocument('i need a new power supply.', 'hardware');
classifier.addDocument('can you play some new music?', 'music');

classifier.train();

console.log(classifier.classify('did the tests pass?')); // -> software 
console.log(classifier.classify('did you buy a new drive?')); // -> hardware 
console.log(classifier.classify('What is the capacity?')); // -> hardware 
console.log(classifier.classify('Lets meet tomorrow?')); // -> meeting 
console.log(classifier.classify('Can you play some stuff?')); // -> music 
```

Could you help me, please?

**Comment by nemo** [comment]
Hey – what version of node do you have? I've only tested this on `4.2.x`.

**Comment by bvanrijn** [comment]
@nemo Hey, thanks for replying so promptly. This is my node version:

```
barend@barend-eos:~/neural$ node -v
v0.10.25
```

**Comment by nemo** [comment]
hey @bvanrijn – unfortunately, any node version below `4.x.x` isn't supported by this module right now. It uses `class` which is only available in the later versions.

**Comment by nemo** [comment]
You can upgrade (or have multiple versions) using [n](https://www.npmjs.com/package/n).

**Comment by bvanrijn** [comment]
Thanks a lot! I think we can close this issue now.
